### ISSUE TITLE
Very serious question

### ISSUE THREAD

**Issue by TheBestTvarynka** [MykytaLiubshin/homework_cpp#1]
I just recently saw your repository and want to ask you the question :grey_question:.
Why you use Visual Studio instead of Clion?
Clion is available on Windows and Linux platform as well.

**Comment by MykytaLiubshin** [comment]
This is my homework and it HAS to be done with Visual Studio. Those are the requirements of my teacher.

**Comment by TheBestTvarynka** [comment]
> This is my homework and it HAS to be done with Visual Studio. Those are the requirements of my teacher.

What a pity( :cry:
